// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRwCfWIKqFx7mg2cfKLAOYjlRbSyPm_Nc',
    appId: '1:671680428689:web:bd78466fe8d35bf9955d30',
    messagingSenderId: '671680428689',
    projectId: 'glucosa-electronica',
    authDomain: 'glucosa-electronica.firebaseapp.com',
    storageBucket: 'glucosa-electronica.appspot.com',
    measurementId: 'G-BQYLYH9H4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvSMFPnP3ZOQvUe1sFN8mC0lNps-g88nM',
    appId: '1:671680428689:android:212d01beb40bf528955d30',
    messagingSenderId: '671680428689',
    projectId: 'glucosa-electronica',
    storageBucket: 'glucosa-electronica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjDXFHXAa2xoP6h4WS7NCa31QdqGBoaBI',
    appId: '1:671680428689:ios:daa6cc1c2310e815955d30',
    messagingSenderId: '671680428689',
    projectId: 'glucosa-electronica',
    storageBucket: 'glucosa-electronica.appspot.com',
    iosBundleId: 'com.example.glucosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjDXFHXAa2xoP6h4WS7NCa31QdqGBoaBI',
    appId: '1:671680428689:ios:955e2a986347993d955d30',
    messagingSenderId: '671680428689',
    projectId: 'glucosa-electronica',
    storageBucket: 'glucosa-electronica.appspot.com',
    iosBundleId: 'com.example.glucosapp.RunnerTests',
  );
}
